
/*
'===============================================================================
'  Generated From - MySQL4_CSharp_BusinessEntity.vbgen
'
'  The supporting base class MySql4Entity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using MySql.Data.MySqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace iMacrosPostingDashboard
{
	public abstract class _affiliateprograms : MySql4Entity
	{
		public _affiliateprograms()
		{
			this.QuerySource = "affiliateprograms";
			this.MappingName = "affiliateprograms";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		public override string GetAutoKeyColumns()
		{
			return "Id";
		}
		

		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return this.Query.Load();
		}
	
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			this.Where.Id.Value = Id;
			
			return this.Query.Load();
		}
		
		
		#region Parameters
		protected class Parameters
		{
			
			public static MySqlParameter Id
			{
				get
				{
					return new MySqlParameter("?Id", MySqlDbType.Int32);

				}
			}
			
			public static MySqlParameter ProgramName
			{
				get
				{
					return new MySqlParameter("?ProgramName", MySqlDbType.VarChar);

				}
			}
			
			public static MySqlParameter PreKeywordLinkPart
			{
				get
				{
					return new MySqlParameter("?PreKeywordLinkPart", MySqlDbType.VarChar);

				}
			}
			
			public static MySqlParameter PostKeywordLinkPart
			{
				get
				{
					return new MySqlParameter("?PostKeywordLinkPart", MySqlDbType.VarChar);

				}
			}
			
			public static MySqlParameter HomePageLink
			{
				get
				{
					return new MySqlParameter("?HomePageLink", MySqlDbType.VarChar);

				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "Id";
            public const string ProgramName = "ProgramName";
            public const string PreKeywordLinkPart = "PreKeywordLinkPart";
            public const string PostKeywordLinkPart = "PostKeywordLinkPart";
            public const string HomePageLink = "HomePageLink";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _affiliateprograms.PropertyNames.Id;
					ht[ProgramName] = _affiliateprograms.PropertyNames.ProgramName;
					ht[PreKeywordLinkPart] = _affiliateprograms.PropertyNames.PreKeywordLinkPart;
					ht[PostKeywordLinkPart] = _affiliateprograms.PropertyNames.PostKeywordLinkPart;
					ht[HomePageLink] = _affiliateprograms.PropertyNames.HomePageLink;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string ProgramName = "ProgramName";
            public const string PreKeywordLinkPart = "PreKeywordLinkPart";
            public const string PostKeywordLinkPart = "PostKeywordLinkPart";
            public const string HomePageLink = "HomePageLink";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _affiliateprograms.ColumnNames.Id;
					ht[ProgramName] = _affiliateprograms.ColumnNames.ProgramName;
					ht[PreKeywordLinkPart] = _affiliateprograms.ColumnNames.PreKeywordLinkPart;
					ht[PostKeywordLinkPart] = _affiliateprograms.ColumnNames.PostKeywordLinkPart;
					ht[HomePageLink] = _affiliateprograms.ColumnNames.HomePageLink;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string ProgramName = "s_ProgramName";
            public const string PreKeywordLinkPart = "s_PreKeywordLinkPart";
            public const string PostKeywordLinkPart = "s_PostKeywordLinkPart";
            public const string HomePageLink = "s_HomePageLink";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string ProgramName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ProgramName);
			}
			set
	        {
				base.Setstring(ColumnNames.ProgramName, value);
			}
		}

		public virtual string PreKeywordLinkPart
	    {
			get
	        {
				return base.Getstring(ColumnNames.PreKeywordLinkPart);
			}
			set
	        {
				base.Setstring(ColumnNames.PreKeywordLinkPart, value);
			}
		}

		public virtual string PostKeywordLinkPart
	    {
			get
	        {
				return base.Getstring(ColumnNames.PostKeywordLinkPart);
			}
			set
	        {
				base.Setstring(ColumnNames.PostKeywordLinkPart, value);
			}
		}

		public virtual string HomePageLink
	    {
			get
	        {
				return base.Getstring(ColumnNames.HomePageLink);
			}
			set
	        {
				base.Setstring(ColumnNames.HomePageLink, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_ProgramName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ProgramName) ? string.Empty : base.GetstringAsString(ColumnNames.ProgramName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ProgramName);
				else
					this.ProgramName = base.SetstringAsString(ColumnNames.ProgramName, value);
			}
		}

		public virtual string s_PreKeywordLinkPart
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PreKeywordLinkPart) ? string.Empty : base.GetstringAsString(ColumnNames.PreKeywordLinkPart);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PreKeywordLinkPart);
				else
					this.PreKeywordLinkPart = base.SetstringAsString(ColumnNames.PreKeywordLinkPart, value);
			}
		}

		public virtual string s_PostKeywordLinkPart
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PostKeywordLinkPart) ? string.Empty : base.GetstringAsString(ColumnNames.PostKeywordLinkPart);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PostKeywordLinkPart);
				else
					this.PostKeywordLinkPart = base.SetstringAsString(ColumnNames.PostKeywordLinkPart, value);
			}
		}

		public virtual string s_HomePageLink
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.HomePageLink) ? string.Empty : base.GetstringAsString(ColumnNames.HomePageLink);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.HomePageLink);
				else
					this.HomePageLink = base.SetstringAsString(ColumnNames.HomePageLink, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ProgramName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ProgramName, Parameters.ProgramName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PreKeywordLinkPart
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PreKeywordLinkPart, Parameters.PreKeywordLinkPart);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PostKeywordLinkPart
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PostKeywordLinkPart, Parameters.PostKeywordLinkPart);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter HomePageLink
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.HomePageLink, Parameters.HomePageLink);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter ProgramName
		    {
				get
		        {
					if(_ProgramName_W == null)
	        	    {
						_ProgramName_W = TearOff.ProgramName;
					}
					return _ProgramName_W;
				}
			}

			public WhereParameter PreKeywordLinkPart
		    {
				get
		        {
					if(_PreKeywordLinkPart_W == null)
	        	    {
						_PreKeywordLinkPart_W = TearOff.PreKeywordLinkPart;
					}
					return _PreKeywordLinkPart_W;
				}
			}

			public WhereParameter PostKeywordLinkPart
		    {
				get
		        {
					if(_PostKeywordLinkPart_W == null)
	        	    {
						_PostKeywordLinkPart_W = TearOff.PostKeywordLinkPart;
					}
					return _PostKeywordLinkPart_W;
				}
			}

			public WhereParameter HomePageLink
		    {
				get
		        {
					if(_HomePageLink_W == null)
	        	    {
						_HomePageLink_W = TearOff.HomePageLink;
					}
					return _HomePageLink_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _ProgramName_W = null;
			private WhereParameter _PreKeywordLinkPart_W = null;
			private WhereParameter _PostKeywordLinkPart_W = null;
			private WhereParameter _HomePageLink_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_ProgramName_W = null;
				_PreKeywordLinkPart_W = null;
				_PostKeywordLinkPart_W = null;
				_HomePageLink_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ProgramName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ProgramName, Parameters.ProgramName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PreKeywordLinkPart
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PreKeywordLinkPart, Parameters.PreKeywordLinkPart);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PostKeywordLinkPart
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PostKeywordLinkPart, Parameters.PostKeywordLinkPart);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter HomePageLink
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.HomePageLink, Parameters.HomePageLink);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter ProgramName
		    {
				get
		        {
					if(_ProgramName_W == null)
	        	    {
						_ProgramName_W = TearOff.ProgramName;
					}
					return _ProgramName_W;
				}
			}

			public AggregateParameter PreKeywordLinkPart
		    {
				get
		        {
					if(_PreKeywordLinkPart_W == null)
	        	    {
						_PreKeywordLinkPart_W = TearOff.PreKeywordLinkPart;
					}
					return _PreKeywordLinkPart_W;
				}
			}

			public AggregateParameter PostKeywordLinkPart
		    {
				get
		        {
					if(_PostKeywordLinkPart_W == null)
	        	    {
						_PostKeywordLinkPart_W = TearOff.PostKeywordLinkPart;
					}
					return _PostKeywordLinkPart_W;
				}
			}

			public AggregateParameter HomePageLink
		    {
				get
		        {
					if(_HomePageLink_W == null)
	        	    {
						_HomePageLink_W = TearOff.HomePageLink;
					}
					return _HomePageLink_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _ProgramName_W = null;
			private AggregateParameter _PreKeywordLinkPart_W = null;
			private AggregateParameter _PostKeywordLinkPart_W = null;
			private AggregateParameter _HomePageLink_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_ProgramName_W = null;
				_PreKeywordLinkPart_W = null;
				_PostKeywordLinkPart_W = null;
				_HomePageLink_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
			
		
		protected override IDbCommand GetInsertCommand()
		{
			MySqlCommand cmd = new MySqlCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText =
			@"INSERT INTO `affiliateprograms`
			(
				`ProgramName`,
				`PreKeywordLinkPart`,
				`PostKeywordLinkPart`,
				`HomePageLink`
			)
			VALUES
			(
				?ProgramName,
				?PreKeywordLinkPart,
				?PostKeywordLinkPart,
				?HomePageLink
			)";

			CreateParameters(cmd);
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			MySqlCommand cmd = new MySqlCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText = 
			@"UPDATE `affiliateprograms` SET 
				`ProgramName`=?ProgramName,
				`PreKeywordLinkPart`=?PreKeywordLinkPart,
				`PostKeywordLinkPart`=?PostKeywordLinkPart,
				`HomePageLink`=?HomePageLink
			WHERE
				`Id`=?Id";

			CreateParameters(cmd);
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			MySqlCommand cmd = new MySqlCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText =
			@"DELETE FROM `affiliateprograms` 
			WHERE
				`Id`=?Id";

	
			MySqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(MySqlCommand cmd)
		{
			MySqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ProgramName);
			p.SourceColumn = ColumnNames.ProgramName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PreKeywordLinkPart);
			p.SourceColumn = ColumnNames.PreKeywordLinkPart;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PostKeywordLinkPart);
			p.SourceColumn = ColumnNames.PostKeywordLinkPart;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.HomePageLink);
			p.SourceColumn = ColumnNames.HomePageLink;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}		
		
	
	}
}
