
// Generated by MyGeneration Version # (1.0.0.4)

using System;

namespace iMacrosPostingDashboard
{

    public class Topicsgeneric : _topicsgeneric
    {
        public Topicsgeneric(string tblname)
        {
            this.QuerySource = tblname;
            this.MappingName = tblname;

            // base.tablename = tblname;
            // this.tablename = tblname;
        }
    }
    
    public class Topicspurseblog : _topicspurseblog
    {
        public Topicspurseblog()
        {

        }
    }

    public class Topicsaskcom : _topicsaskcom
    {
        public Topicsaskcom()
        {

        }
    }
    
    public class Topicsfamiljeliv : _topicsfamiljeliv
	{
		public Topicsfamiljeliv()
		{
		
		}
	}

    public class Topicsmumsnet : _topicsmumsnet
	{
		public Topicsmumsnet()
		{
		
		}
	}
	public class Topicsgutefrage : _topicsgutefrage
	{
		public Topicsgutefrage()
		{
		
		}
	}
	public class Config : _config
	{
		public Config()
		{
		
		}
	}
	public class Emailaccounts : _emailaccounts
	{
		public Emailaccounts()
		{
		
		}
	}
	public class Projects : _projects
	{
		public Projects()
		{
		
		}
	}
	public class Proxies : _proxies
	{
		public Proxies()
		{
		
		}
	}
	public class Responses : _responses
	{
		public Responses()
		{
		
		}
	}
	public class Affiliateprograms : _affiliateprograms
	{
		public Affiliateprograms()
		{
		
		}
	}	
}

