
/*
'===============================================================================
'  Generated From - MySQL4_CSharp_BusinessEntity.vbgen
'
'  The supporting base class MySql4Entity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using MySql.Data.MySqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace iMacrosPostingDashboard
{
	public abstract class _responses : MySql4Entity
	{
		public _responses()
		{
			this.QuerySource = "responses";
			this.MappingName = "responses";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		public override string GetAutoKeyColumns()
		{
			return "Id";
		}
		

		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return this.Query.Load();
		}
	
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			this.Where.Id.Value = Id;
			
			return this.Query.Load();
		}
		
		
		#region Parameters
		protected class Parameters
		{
			
			public static MySqlParameter Id
			{
				get
				{
					return new MySqlParameter("?Id", MySqlDbType.Int32);

				}
			}
			
			public static MySqlParameter Response
			{
				get
				{
					return new MySqlParameter("?Response", MySqlDbType.Blob);

				}
			}
			
			public static MySqlParameter ResponseGroup
			{
				get
				{
					return new MySqlParameter("?ResponseGroup", MySqlDbType.VarChar);

				}
			}
			
			public static MySqlParameter RespGrSpecSequence
			{
				get
				{
					return new MySqlParameter("?RespGrSpecSequence", MySqlDbType.Int32);

				}
			}
			
			public static MySqlParameter LanguageId
			{
				get
				{
					return new MySqlParameter("?LanguageId", MySqlDbType.Int32);

				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "Id";
            public const string Response = "Response";
            public const string ResponseGroup = "ResponseGroup";
            public const string RespGrSpecSequence = "RespGrSpecSequence";
            public const string LanguageId = "LanguageId";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _responses.PropertyNames.Id;
					ht[Response] = _responses.PropertyNames.Response;
					ht[ResponseGroup] = _responses.PropertyNames.ResponseGroup;
					ht[RespGrSpecSequence] = _responses.PropertyNames.RespGrSpecSequence;
					ht[LanguageId] = _responses.PropertyNames.LanguageId;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Response = "Response";
            public const string ResponseGroup = "ResponseGroup";
            public const string RespGrSpecSequence = "RespGrSpecSequence";
            public const string LanguageId = "LanguageId";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _responses.ColumnNames.Id;
					ht[Response] = _responses.ColumnNames.Response;
					ht[ResponseGroup] = _responses.ColumnNames.ResponseGroup;
					ht[RespGrSpecSequence] = _responses.ColumnNames.RespGrSpecSequence;
					ht[LanguageId] = _responses.ColumnNames.LanguageId;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Response = "s_Response";
            public const string ResponseGroup = "s_ResponseGroup";
            public const string RespGrSpecSequence = "s_RespGrSpecSequence";
            public const string LanguageId = "s_LanguageId";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Response
	    {
			get
	        {
				return base.Getstring(ColumnNames.Response);
			}
			set
	        {
				base.Setstring(ColumnNames.Response, value);
			}
		}

		public virtual string ResponseGroup
	    {
			get
	        {
				return base.Getstring(ColumnNames.ResponseGroup);
			}
			set
	        {
				base.Setstring(ColumnNames.ResponseGroup, value);
			}
		}

		public virtual int RespGrSpecSequence
	    {
			get
	        {
				return base.Getint(ColumnNames.RespGrSpecSequence);
			}
			set
	        {
				base.Setint(ColumnNames.RespGrSpecSequence, value);
			}
		}

		public virtual int LanguageId
	    {
			get
	        {
				return base.Getint(ColumnNames.LanguageId);
			}
			set
	        {
				base.Setint(ColumnNames.LanguageId, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Response
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Response) ? string.Empty : base.GetstringAsString(ColumnNames.Response);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Response);
				else
					this.Response = base.SetstringAsString(ColumnNames.Response, value);
			}
		}

		public virtual string s_ResponseGroup
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ResponseGroup) ? string.Empty : base.GetstringAsString(ColumnNames.ResponseGroup);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ResponseGroup);
				else
					this.ResponseGroup = base.SetstringAsString(ColumnNames.ResponseGroup, value);
			}
		}

		public virtual string s_RespGrSpecSequence
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RespGrSpecSequence) ? string.Empty : base.GetintAsString(ColumnNames.RespGrSpecSequence);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RespGrSpecSequence);
				else
					this.RespGrSpecSequence = base.SetintAsString(ColumnNames.RespGrSpecSequence, value);
			}
		}

		public virtual string s_LanguageId
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.LanguageId) ? string.Empty : base.GetintAsString(ColumnNames.LanguageId);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LanguageId);
				else
					this.LanguageId = base.SetintAsString(ColumnNames.LanguageId, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Response
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Response, Parameters.Response);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ResponseGroup
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ResponseGroup, Parameters.ResponseGroup);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RespGrSpecSequence
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RespGrSpecSequence, Parameters.RespGrSpecSequence);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter LanguageId
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.LanguageId, Parameters.LanguageId);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Response
		    {
				get
		        {
					if(_Response_W == null)
	        	    {
						_Response_W = TearOff.Response;
					}
					return _Response_W;
				}
			}

			public WhereParameter ResponseGroup
		    {
				get
		        {
					if(_ResponseGroup_W == null)
	        	    {
						_ResponseGroup_W = TearOff.ResponseGroup;
					}
					return _ResponseGroup_W;
				}
			}

			public WhereParameter RespGrSpecSequence
		    {
				get
		        {
					if(_RespGrSpecSequence_W == null)
	        	    {
						_RespGrSpecSequence_W = TearOff.RespGrSpecSequence;
					}
					return _RespGrSpecSequence_W;
				}
			}

			public WhereParameter LanguageId
		    {
				get
		        {
					if(_LanguageId_W == null)
	        	    {
						_LanguageId_W = TearOff.LanguageId;
					}
					return _LanguageId_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Response_W = null;
			private WhereParameter _ResponseGroup_W = null;
			private WhereParameter _RespGrSpecSequence_W = null;
			private WhereParameter _LanguageId_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Response_W = null;
				_ResponseGroup_W = null;
				_RespGrSpecSequence_W = null;
				_LanguageId_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Response
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Response, Parameters.Response);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ResponseGroup
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ResponseGroup, Parameters.ResponseGroup);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RespGrSpecSequence
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RespGrSpecSequence, Parameters.RespGrSpecSequence);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter LanguageId
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.LanguageId, Parameters.LanguageId);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Response
		    {
				get
		        {
					if(_Response_W == null)
	        	    {
						_Response_W = TearOff.Response;
					}
					return _Response_W;
				}
			}

			public AggregateParameter ResponseGroup
		    {
				get
		        {
					if(_ResponseGroup_W == null)
	        	    {
						_ResponseGroup_W = TearOff.ResponseGroup;
					}
					return _ResponseGroup_W;
				}
			}

			public AggregateParameter RespGrSpecSequence
		    {
				get
		        {
					if(_RespGrSpecSequence_W == null)
	        	    {
						_RespGrSpecSequence_W = TearOff.RespGrSpecSequence;
					}
					return _RespGrSpecSequence_W;
				}
			}

			public AggregateParameter LanguageId
		    {
				get
		        {
					if(_LanguageId_W == null)
	        	    {
						_LanguageId_W = TearOff.LanguageId;
					}
					return _LanguageId_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Response_W = null;
			private AggregateParameter _ResponseGroup_W = null;
			private AggregateParameter _RespGrSpecSequence_W = null;
			private AggregateParameter _LanguageId_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Response_W = null;
				_ResponseGroup_W = null;
				_RespGrSpecSequence_W = null;
				_LanguageId_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
			
		
		protected override IDbCommand GetInsertCommand()
		{
			MySqlCommand cmd = new MySqlCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText =
			@"INSERT INTO `responses`
			(
				`Response`,
				`ResponseGroup`,
				`RespGrSpecSequence`,
				`LanguageId`
			)
			VALUES
			(
				?Response,
				?ResponseGroup,
				?RespGrSpecSequence,
				?LanguageId
			)";

			CreateParameters(cmd);
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			MySqlCommand cmd = new MySqlCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText = 
			@"UPDATE `responses` SET 
				`Response`=?Response,
				`ResponseGroup`=?ResponseGroup,
				`RespGrSpecSequence`=?RespGrSpecSequence,
				`LanguageId`=?LanguageId
			WHERE
				`Id`=?Id";

			CreateParameters(cmd);
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			MySqlCommand cmd = new MySqlCommand();
			cmd.CommandType = CommandType.Text;
			cmd.CommandText =
			@"DELETE FROM `responses` 
			WHERE
				`Id`=?Id";

	
			MySqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(MySqlCommand cmd)
		{
			MySqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Response);
			p.SourceColumn = ColumnNames.Response;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ResponseGroup);
			p.SourceColumn = ColumnNames.ResponseGroup;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RespGrSpecSequence);
			p.SourceColumn = ColumnNames.RespGrSpecSequence;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.LanguageId);
			p.SourceColumn = ColumnNames.LanguageId;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}		
		
	
	}
}
